#!/bin/bash -l

GIT_REPO=$HOME/mfg-website
TMP_GIT_CLONE=$HOME/tmp/git/
PUBLIC_WWW=/var/www/html

git clone $GIT_REPO $TMP_GIT_CLONE
sudo jekyll build --source $TMP_GIT_CLONE --destination $PUBLIC_WWW
rm -Rf $TMP_GIT_CLONE
exit
